// Auth
export const AUTHENTICATING = 'AUTHENTICATING';
export const LOGIN = 'LOGIN';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT = 'LOGOUT';

//Navigation
export const GOTO_SCREEN = 'GOTO_SCREEN';
export const GOTO_GUEST_TAB_BAR = 'GOTO_GUEST_TAB_BAR';

//Section Changed
export const GOTO_SECTION = 'GOTO_SECTION';

//WebRTC
export const CONNECT = 'CONNECT';
export const UPDATE_CONNECTION_STATUS = 'UPDATE_CONNECTION_STATUS';
export const SWITCH_CAMERA = 'SWITCH_CAMERA';
export const SET_VIDEO_SOURCE = 'SET_VIDEO_SOURCE';
export const UPDATE_TEXT_ROOM_DATA = 'UPDATE_TEXT_ROOM_DATA';
export const UPDATE_INFO = 'UPDATE_INFO';
export const UPDATE_CHANNEL_LIST = 'UPDATE_CHANNEL_LIST';
export const SET_TEXT_ROOM_CONNECTED_STATE = 'SET_TEXT_ROOM_CONNECTED_STATE';
export const SET_ROOM = 'SET_ROOM';
export const SET_ROOM_ID = 'SET_ROOM_ID';
export const REMOVE_PEER = 'REMOVE_PEER';
