platform :ios, '9.0'
target 'NavTestV1' do
  react_native_path = "../node_modules/react-native"
  pod "yoga", :path => "#{react_native_path}/ReactCommon/Yoga"
  pod "React", :path => react_native_path, subspecs: [
    'RCTImage',
    'DevSupport',
    'Core',
    'CxxBridge',
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket',
    'RCTNetwork',
  ]
  pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'
  pod 'GoogleMaps'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Firebase/Messaging'

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

end
