platform :ios, '9.0'
target 'Homecast' do
  react_native_path = "../node_modules/react-native"
  pod "yoga", :path => "#{react_native_path}/ReactCommon/Yoga"
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod "React", :path => react_native_path, subspecs: [
    'RCTImage',
    'DevSupport',
    'Core',
    'CxxBridge',
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket',
    'RCTNetwork',
  ]
  pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'
  pod 'GoogleMaps'
  pod 'Firebase/Core', '~> 5.15.0'
  pod 'Firebase/Messaging'

#  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

#  pod 'react-native-google-analytics-bridge', :path => '../node_modules/react-native-google-analytics-bridge'


  pod 'react-native-maps', :path => '../node_modules/react-native-maps'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-webrtc', :path => '../node_modules/react-native-webrtc'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == "React"
        target.remove_from_project
      end
    end
  end

end
